package main

import (
	"context"
	"fmt"
	"log"
	"os"
	"strconv"
	"strings"
	"time"

	"github.com/gocolly/colly"
	"github.com/joho/godotenv"
	"go.mongodb.org/mongo-driver/v2/bson"
	"go.mongodb.org/mongo-driver/v2/mongo"
	"go.mongodb.org/mongo-driver/v2/mongo/options"
	"go.mongodb.org/mongo-driver/v2/mongo/readpref"
)

// A PriceRecord stores the price data of a Steam game at a current time
type PriceRecord struct {
	OriginalPrice float64   `bson:"original_price" json:"original_price"` // Price without discount
	DiscountPrice float64   `bson:"discount_price" json:"discount_price"` // Price with discount
	Discount      float64   `bson:"discount" json:"discount"`             // Discount perceent (multiplied by 100)
	CheckedAt     time.Time `bson:"checked_at" json:"checked_at"`         // Last time the price was checked
}

// A Game represents the Steam game data
type Game struct {
	AppId         int           `bson:"_id" json:"app_id"`                    // The unique app ID generated by steam
	Title         string        `bson:"title" json:"title"`                   // The game's title
	URL           string        `bson:"url" json:"url"`                       // The game's webpage
	PriceSnapshot PriceRecord   `bson:"price_snapshot" json:"price_snapshot"` // The game's price data currently
	PriceHistory  []PriceRecord `bson:"price_history" json:"price_history"`   // The game's price history over time
}

// connectMongoDB establishes a connection to the MongoDB
//
// On success, connectMongoDB returns a MongoDB client and null error.
// On failure, it returns null client and a Connect/Ping error
func connectMongoDB() (*mongo.Client, error) {
	// Load the .env file and log the error if it odes not exists
	if err := godotenv.Load(); err != nil {
		log.Println("No .env file found, relying on real environment variables")
	}

	// Get the MONGO_URI variable and log the error
	// if it is not set
	mongoURI := os.Getenv("MONGO_URI")
	if mongoURI == "" {
		log.Fatal("MONGO_URI environment variable not set")
	}

	// Establish a connection to MongoDB and instantiate a mongoDB client
	//
	// Log an error if a connection fails
	client, err := mongo.Connect(options.Client().ApplyURI(mongoURI))
	if err != nil {
		log.Fatal(err)
	}

	// Create a context and ping the MongoDB, giving it a 2 second deadline
	//
	// If it fails to ping, return a null client and an error
	// Otherwise, return the client and a null error
	ctx, cancel := context.WithTimeout(context.Background(), 2*time.Second)
	defer cancel()

	if err := client.Ping(ctx, readpref.Primary()); err != nil {
		client.Disconnect(context.Background())
		return nil, err
	}

	return client, nil
}

// upsertGame inserts a game and its price record into the Game document
// if it does not exist. Otherwise, it will update the price history
// if there has been a change, i.e., discount change or price change
func upsertGame(collection *mongo.Collection, g Game) error {
	// Search for the game inside the Game document using its
	// app id.
	//
	// If it does not exists, insert into the document
	// and return the error if there was one.
	var existing Game
	err := collection.FindOne(
		context.TODO(),
		bson.M{"_id": g.AppId},
	).Decode(&existing)

	if err == mongo.ErrNoDocuments {
		_, insertErr := collection.InsertOne(context.TODO(), g)
		return insertErr
	}

	// If there is an error but insertion failed, return it
	if err != nil {
		return err
	}

	// Get the game's current price
	rec := g.PriceSnapshot

	// Get the last price record from its price history
	last := existing.PriceHistory[len(existing.PriceHistory)-1]

	// True under any of the following condition
	// - The game does not have a pre-existing price history
	// - The last discount price does not match the current discount price
	// - The last original price does not match the current original price
	changed := len(existing.PriceHistory) == 0 ||
		last.DiscountPrice != rec.DiscountPrice ||
		last.OriginalPrice != rec.OriginalPrice

	// Initialize an update variable to update/set these
	// 3 specific field
	update := bson.M{
		"$set": bson.M{
			"price_snapshot": rec,
			"title":          g.Title,
			"url":            g.URL,
		},
	}

	// If there was a change in the game's price history, add it to the
	// update map
	if changed {
		update["$push"] = bson.M{"price_history": rec}
	}

	// Update the game with the field using its app id and return the error
	_, err = collection.UpdateOne(context.TODO(), bson.M{"_id": g.AppId}, update)
	return err
}

// parsePaginationData crawls the steam store webpage's pagination
// section and extracts the total no. of pages.
func parsePaginationData(totalPages *int) {
	// Insantiate a Collecter instance to begin scraping
	c := colly.NewCollector(
		colly.UserAgent("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"),
	)

	// Scrape this specific part of the HTML, extracting the total page count
	c.OnHTML("div.search_pagination > div.search_pagination_right", func(e *colly.HTMLElement) {
		e.ForEach("a[href]", func(_ int, el *colly.HTMLElement) {
			page, err := strconv.Atoi(strings.TrimSpace(el.Text))
			if err != nil {
				return
			}

			if page > *totalPages {
				*totalPages = page
			}
		})
	})

	// Print the URL being visted
	c.OnRequest(func(r *colly.Request) {
		fmt.Println("Visiting:", r.URL)
	})

	// Print any error that happens during the scraping
	c.OnError(func(r *colly.Response, err error) {
		fmt.Println("Request error:", err)
	})

	// Visit the Steam store page and log the error if it exists
	var err = c.Visit("https://store.steampowered.com/search?hwtype=0&supportedlang=english&hidef2p=1&ndl=1&page=1")
	if err != nil {
		log.Fatal(err)
	}
}

// extractValue extracts the floating point value from a Steam game, specifically
// its price (original and discount) and the discount percent
func extractValue(s string) (float64, error) {
	// Remove all leading and trailing whitespaces
	s = strings.TrimSpace(s)

	// Extract and return the discount off percent
	if strings.HasSuffix(s, "%") {
		s = strings.TrimSuffix(s, "%")
		return strconv.ParseFloat(strings.TrimSpace(s), 64)
	}

	// Extract and return the price
	if strings.HasPrefix(s, "$") {
		s = strings.TrimPrefix(s, "$")
		return strconv.ParseFloat(strings.TrimSpace(s), 64)
	}

	// Return an error if value could not be extracted
	return 0, fmt.Errorf("unsupported value: %q", s)
}

// cleanURL cleans up the Steam game webpage link by removing
// the serial number.
//
// Input: https://store.steampowered.com/app/<app id>/<title>/?snr=<serial no.>
// Output: https://store.steampowered.com/app/<app id>/<title>/
func cleanURL(href string) string {
	if idx := strings.Index(href, "?"); idx != -1 {
		return href[:idx]
	}
	return href
}

// track crawls the Steam store webpage and collects the game data into a MongoDB collection
func track(collection *mongo.Collection) {
	// Extract the total no. of pages from the pagination data
	var totalPages int
	parsePaginationData(&totalPages)
	fmt.Printf("total_pages=%d\n", totalPages)

	// Initialize a Collector instance to begin crawling
	c := colly.NewCollector(
		colly.UserAgent("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"),
	)

	// Setup a delay to avoid hitting the page too many times and triggering its rate limit
	c.Limit(&colly.LimitRule{
		Delay:       90 * time.Second,
		RandomDelay: 30 * time.Second,
	})
	c.SetRequestTimeout(30 * time.Second)

	// Search the Steam store games list
	c.OnHTML("div#search_resultsRows > a", func(e *colly.HTMLElement) {
		// Extract the discount, original price, and discount price
		discount, _ := extractValue(e.ChildText("div.discount_pct"))

		original_price, _ := extractValue(e.ChildText("div.discount_original_price"))

		discount_price, _ := extractValue(e.ChildText("div.discount_final_price"))

		// Extract the game's app id and end the crawling if there was
		// an error
		id, err := strconv.Atoi(e.Attr("data-ds-appid"))
		if err != nil {
			return
		}

		// If the game does not have a discount, set the original price
		// and the discount price to be the same
		//
		// Context: Steam puts the final price in the discount field
		// even if there is no discount
		if e.DOM.Find("div.discount_block").HasClass("no_discount") {
			original_price = discount_price
			discount = 0
		}

		// Create a PriceRecord data at the most recent time checked
		price := PriceRecord{
			OriginalPrice: original_price,
			DiscountPrice: discount_price,
			Discount:      discount,
			CheckedAt:     time.Now(),
		}

		// Create a Game data storing
		// - id
		// - title
		// - url
		// - current price snapshot data
		// - price history
		game := Game{
			AppId:         id,
			Title:         e.ChildText("span.title"),
			URL:           cleanURL(e.Attr("href")),
			PriceSnapshot: price,
			PriceHistory:  []PriceRecord{price},
		}

		// Upsert the game into the Game document and throw an error if it fails
		if err := upsertGame(collection, game); err != nil {
			fmt.Println("Upsert error:", err)
		}

	})

	// Print out the current page being visited
	c.OnRequest(func(r *colly.Request) {
		fmt.Println("Visiting:", r.URL)
	})

	// Print out the error during scraping
	c.OnError(func(r *colly.Response, err error) {
		fmt.Println("Request error:", err)
	})

	// Visit all pages starting from 1 to n and log any errors that occurs
	// during visit
	for page := 1; page <= 5; page++ {
		url := fmt.Sprintf("https://store.steampowered.com/search?hwtype=0&supportedlang=english&hidef2p=1&ndl=1&page=%d", page)
		var err = c.Visit(url)
		if err != nil {
			log.Fatal(err)
		}
	}

}

func main() {
	// Establish a connection to MongoDB
	client, err := connectMongoDB()
	if err != nil {
		log.Fatal("Could not connect to MongoDB:", err)
	}

	// Dissconnect if there was an issue with connecting
	defer func() {
		if err := client.Disconnect(context.Background()); err != nil {
			log.Println("MongoDB disconnect error:", err)
		}
	}()

	// Connect to the Steam Price Tracker database and get the GAME collection
	collection := client.Database("steam_price_tracker").Collection("game")

	// Start scraping the webpage
	track(collection)
}
