package types

import "time"

// A PriceRecord stores the price data of a Steam game at a current time
type PriceRecord struct {
	OriginalPrice float64   `bson:"original_price" json:"original_price"` // Price without discount
	DiscountPrice float64   `bson:"discount_price" json:"discount_price"` // Price with discount
	Discount      float64   `bson:"discount" json:"discount"`             // Discount perceent (multiplied by 100)
	CheckedAt     time.Time `bson:"checked_at" json:"checked_at"`         // Last time the price was checked
}

// A Game represents the Steam game data
type Game struct {
	AppId         int           `bson:"_id" json:"app_id"`                    // The unique app ID generated by steam
	Title         string        `bson:"title" json:"title"`                   // The game's title
	URL           string        `bson:"url" json:"url"`                       // The game's webpage
	PriceSnapshot PriceRecord   `bson:"price_snapshot" json:"price_snapshot"` // The game's price data currently
	PriceHistory  []PriceRecord `bson:"price_history" json:"price_history"`   // The game's price history over time
}
