package types

import (
	"time"

	"go.mongodb.org/mongo-driver/v2/mongo"
)

// A PriceRecord stores the price data of a Steam game at a current time
type PriceRecord struct {
	OriginalPrice float64   `bson:"original_price" json:"original_price"` // Price without discount
	DiscountPrice float64   `bson:"discount_price" json:"discount_price"` // Price with discount
	Discount      int64     `bson:"discount" json:"discount"`             // Discount perceent (multiplied by 100)
	CheckedAt     time.Time `bson:"checked_at" json:"checked_at"`         // Last time the price was checked
}

// A Game represents the Steam game data
type Game struct {
	AppId         int           `bson:"_id" json:"app_id"`                    // The unique app ID generated by steam
	Title         string        `bson:"title" json:"title"`                   // The game's title
	URL           string        `bson:"url" json:"url"`                       // The game's webpage
	PriceSnapshot PriceRecord   `bson:"price_snapshot" json:"price_snapshot"` // The game's price data currently
	PriceHistory  []PriceRecord `bson:"price_history" json:"price_history"`   // The game's price history over time
}

type Metadata struct {
	ID         string    `bson:"_id"`
	LastPage   int       `bson:"last_page"`
	TotalPages int       `bson:"total_pages"`
	UpdatedAt  time.Time `bson:"updated_at"`
}

type App struct {
	Games *mongo.Collection
	State *mongo.Collection
}

type Options struct {
	ID     int
	Page   int
	Filter string
}

type Command func(app *App, opts Options) error
